title: The title of your theme

nav_logo_file: assets/img/rse-ops-text.png
footer_logo_file: assets/img/rse-ops-circle.png

permalink: pretty
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: true

github_link: true
github_pages_branch: main

exclude:
 - _assets
 - Gemfile
 - Gemfile.lock
 - vendor
 - .github
